Foro. Flask/foro/views.py
from unicodedata import category, name
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app, jsonify
from flask_login import login_required, current_user
from .models import User, Post, Post_Category, Profile_Comment, Profile_Comment_Like
from . import db
from werkzeug.security import check_password_hash, generate_password_hash
import json
import os
from datetime import datetime
from .functions import save_images, check_files_on_update

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():

    users_array = []
    users_on = []

    if request.method == "POST":
        pass

    if request.method == 'GET':
        users_db = User.query.limit(10).all()
        users_db_ons = User.query.all()
        categorys = Post_Category.query.all()
        
        time_now = datetime.utcnow()

        for user in users_db_ons:
            time_afk = time_now - user.is_active
            time_afk = str(time_afk)
            values_time = time_afk.split(":")
            minutes = int(values_time[1])
            if minutes < 5:
                users_on.append(user)
        
        for user in users_db:
            user_json = {"img": user.profile_photo,
            "nick": user.username,
            "id": user.id,}
            users_array.append(user_json)

        return render_template("index.html", user=current_user, users = users_db, usersjson = users_array, users_on = users_on, categorys = categorys)


@views.route('/profile/<user>', methods= ['GET', 'POST'])
@login_required
def profile(user):
    user_db = User.query.filter_by(username=user).first()
    profile_comments_db = db.session.query(User,Profile_Comment).join(Profile_Comment).filter_by(profile_id = user_db.id)

    if request.method == 'POST':

        content = request.form.get('comment')

        new_comment = Profile_Comment(content = content,user_id = current_user.id, profile_id = user_db.id)
        db.session.add(new_comment)
        db.session.commit()

        if user_db and user == current_user.username:
            return redirect(url_for('views.profile', user = current_user.username))
        else:
            return redirect(url_for('views.profile', user = user_db.username))

    if request.method == 'GET':

        if user_db and user == current_user.username:
            return render_template('profile.html', user=current_user, comments = profile_comments_db)
        elif user_db and user == user_db.username:
            return render_template('profile.html', user=user_db, comments = profile_comments_db)
        else:
            return render_template("<h2>User Not Found</h2>")

@views.route('/profile/edit/<username>', methods = ['GET', 'POST'])
@login_required
def profile_update(username):
    
    user_db = User.query.filter_by(username=username).first()
    profile_comments_db = db.session.query(User,Profile_Comment).join(Profile_Comment).filter_by(profile_id = user_db.id)

    # El update se va a cargar solo si el usuario que se pasa por url es igual al usuario logeado.
    if username == current_user.username:

        if request.method == "POST":
            # Obtenemos todos los datos del form.
            username = request.form.get('username')
            email = request.form.get('email')
            profile_photo = request.files.get('profile_photo')
            remove_profile_photo = request.form.get('removeprofilephoto')
            profile_banner = request.files.get('profile_banner')
            remove_profile_banner = request.form.get('removeprofilebanner')
            password = request.form.get('password')

            # Obtenemos si el username existe en la base de datos al igual que el mail.
            user_db = User.query.filter_by(username=username).first()
            email_db = User.query.filter_by(email=email).first()


            # Chequea si todos los datos del update al dar update son iguales, es decir, si no fueron editados.
            if (user_db and user_db.username == username) and user_db.email == email and not profile_photo and not remove_profile_photo == "on" and not profile_banner and not remove_profile_banner == "on":
                flash("You cant edit with the same information.", category="error")
                return redirect(url_for('views.profile', user = current_user.username))
            else:
                # Si no existe dicho usuario.
                if not user_db or user_db.username == current_user.username:
                    # Si no existe dicho email.
                    if not email_db or email_db.email == current_user.email:
                        # Si la contraseña pasada es igual a la contraseña encriptada en la base de datos
                        if check_password_hash(current_user.password, password):

                            current_user.username = username
                            current_user.email = email
                            current_profile_photo_user = current_user.profile_photo 
                            current_profile_banner_user = current_user.profile_banner 

                            current_user.profile_photo = check_files_on_update(current_profile_photo_user, profile_photo, current_app, remove_profile_photo, "profilephotos", "default.webp")
                            current_user.profile_banner = check_files_on_update(current_profile_banner_user, profile_banner, current_app, remove_profile_banner, "profilebanners", "default.jpg") 

                            db.session.commit()
                            return redirect(url_for('views.profile', user = current_user.username))   
                        else:
                            flash("The changes could not be applied because the password is invalid.", category="error")
                            return redirect(url_for('views.profile', user = current_user.username))
                    else:
                        flash("The changes could not be applied because the email already exists.", category="error")
                        return redirect(url_for('views.profile', user = current_user.username))
                else:
                    flash("The changes could not be applied because the user already exists.", category="error")
                    return redirect(url_for('views.profile', user = current_user.username))

                         

        return render_template('update.html', user=current_user, comments = profile_comments_db)
    else:
        return "<h2>User Not Found</h2>"


@views.route("/<user>/<comment_id>/like", methods=['GET'])
@login_required
def like(user, comment_id):
    comment = Profile_Comment.query.filter_by(id = comment_id).first()
    user_db = User.query.filter_by(id=comment.profile_id).first()
    like = Profile_Comment_Like.query.filter_by(user_id = current_user.id, comment_id = comment_id).first()

    if not comment:
        flash('Comment does not exist.', category="error")
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        like = Profile_Comment_Like(user_id = current_user.id, comment_id = comment_id)
        db.session.add(like)
        db.session.commit()

    if user_db:
        return redirect(url_for('views.profile', user = user_db.username))

@views.route("<user>/<comment_id>/delete")
@login_required
def delete_comment(user ,comment_id):
    comment = Profile_Comment.query.filter_by(id = comment_id).first()


    if not comment:
        flash('Comment does not exist.', category="error")
    else:
        user_db = User.query.filter_by(id=comment.profile_id).first()

        db.session.delete(comment)
        db.session.commit()

        if user_db:
            return redirect(url_for('views.profile', user = user_db.username))

    return redirect(url_for('views.profile', user = user))


@views.before_request
@login_required
def update_user_is_active():
    current_user.is_active = datetime.utcnow()
    db.session.commit()

@views.route('/posts/<category_id>', methods = ['GET'])
@login_required
def posts(category_id):

    posts_db = db.session.query(User,Post).join(Post).filter_by(category_id = category_id)
    print(posts_db)
    category = Post_Category.query.filter_by(id = category_id).first()

    return render_template('posts.html', user=current_user, posts = posts_db, category = category)

@views.route('/posts/<category_id>/create-post', methods=['GET', 'POST'])
@login_required
def create_post(category_id):
    category = Post_Category.query.filter_by(id = category_id).first()

    if request.method == "POST":
        post_title = request.form.get('title_post').strip()
        post_content = request.form.get('content_post').strip()
        post_user_id = current_user.id
        post_category_id = category_id
        
        if post_title and post_content and post_user_id and post_category_id:
            new_post = Post(title=post_title, content=post_content, user_id = post_user_id, category_id = post_category_id)
            db.session.add(new_post)
            db.session.commit()
            flash("Post created.", category="success")
            return redirect(url_for('views.posts', category_id = category_id))
        else:
            flash("You failed to create the post.", category="error")
            return redirect(url_for('views.posts', category_id = category_id))

    if request.method == "GET":
        return render_template('post_create.html', user=current_user, category = category)

@views.route('/posts/<category_id>/<title>', methods = ['GET'])
@login_required
def post(category_id, title):

    post_db = Post.query.filter_by(title = title).first()

    return render_template('post.html', user=current_user, post = post_db)

Foro. Flask/foro/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/general.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/navbar.css') }}">
    {% block linkcss %} {% endblock linkcss %}

    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>

    <header class="header_container">
        <div class="navbar_mobile">
            <img src="{{ url_for('static', filename='DL.png') }}" alt="Diego Libonati Logo">
            <i class="bi bi-list"></i>
            <i class="bi bi-x"></i>
        </div>

        {% if user.is_authenticated %}
          <div class="navbar_logo">
            <img  src="{{ url_for('static', filename='profilephotos/'+current_user.profile_photo) }}" alt="gif">
            <h2>¡{{current_user.username}}!</h2>
          </div>
        {% endif %}

        <nav class="navbar_container">
            <ul class="navbar_container_list">
              {% if user.is_authenticated %}
                <li class="navbar_container_list_li"><a class="navbar_container_list_li_a" href="/">Home</a></li>
                <li class="navbar_container_list_li"><a class="navbar_container_list_li_a" href={{ url_for('views.profile', user = current_user.username) }}>Profile</a></li>
                <li class="navbar_container_list_li"><a class="navbar_container_list_li_a" href="/logout">Log out</a></li>
              {% else %}
                <li class="navbar_container_list_li"><a class="navbar_container_list_li_a" href="/login">Login</a></li>
                <li class="navbar_container_list_li"><a class="navbar_container_list_li_a" href="/sign-up">Sign Up</a></li>
              {% endif %}
            </ul>
        </nav>
    </header>

    {% with messages = get_flashed_messages(with_categories=true) %} 

      {% if messages %} 
      
        {% for category, message in messages %} 
        
          {% if category == 'error' %}

              <section class="alert bad">
                <h2>{{message}}</h2>
                <h2 class="quit-alert">X</h2>
              </section>
        
            {% else %}
          
              <section class="alert good">
                <h2>{{message}}</h2>
                <h2 class="quit-alert">X</h2>
              </section>
        
            {% endif %} 
          
          {% endfor %} 
        
        {% endif %} 
      
      {% endwith %}

      {% block content %}
    
      {% endblock content %}

    <script src="{{ url_for('static', filename='js/general.js') }}"></script>
    <script src="{{ url_for('static', filename='js/navbar.js') }}"></script>
    {% block javascript %} {% endblock javascript %}
  </body>
</html>

Foro. Flask/foro/templates/index.html
{% extends 'base.html' %}

{% block linkcss %} 
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home/users.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home/chat.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home/ons.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home/categorys.css') }}">
{% endblock linkcss %}

{% block title %} Home {% endblock title %}

{% block content %}
    <main>
        <section class="users_container" data-users='{{ usersjson | tojson }}'>
            <h2>Some users </h2>
            
            <article class="users_container_list">
                {% for user in users %}
                <div id="{{user.id}}_container" class="cards">
                    <img class="" src="{{ url_for('static', filename='profilephotos/'+user.profile_photo) }}" alt="{{user.username}}">
                </div>
                {% endfor %}
            </article>
        </section>

        <section class="chat_container">
            <ul class="chat_messages">

            </ul>

            <form> 
                <input type="text" placeholder="Your message" id="myMessage" class="inputMessage"></input>
                <button id="sendbutton">SUBMIT</button>
            </form>
        </section>

        <section class="categorys_container">
            {% for category in categorys %}
                <article class="category_container">
                    <img src="{{ url_for('static', filename='categoryimages/'+category.image) }}" alt="category"> 
                    <div class="category_container_information">
                        <a href="{{url_for('views.posts', category_id = category.id)}}">JOIN TO {{category.name}}</a>
                    </div>
                </article>
            {% endfor %}
        </section>

        <section class="ons_container">
            <h2>Users ON</h2>
            <ul class="ons_container_list">
                {% for user in users_on %}
                    <li>{{user.username}}</li>
                {% endfor %}
            </ul>
        </section>
    </main>
{% endblock content %}

{% block javascript %} 

    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.5.1/socket.io.js" ></script>

    <script src="{{ url_for('static', filename='js/home/users.js') }}"> </script>

    <script src="{{ url_for('static', filename='js/home/socketio.js') }}"> </script>

{% endblock javascript %}

Foro. Flask/foro/templates/login.html
{% extends 'base.html' %}

{% block linkcss %} <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login/login.css') }}">{% endblock linkcss %}

{% block title %} Login {% endblock title %}

{% block content %}
<main>
    <section class="form_login_center">
        <form method="POST" class="form_container">
            <label for="username">Username:</label>
            <input type="text" id="username" name="username">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password">
            <button type="submit">Login</button>
        </form>
    </section>
</main>
{% endblock content %}

Foro. Flask/foro/templates/post.html
{% extends 'base.html' %}

{% block linkcss %} 
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/posts/post.css') }}">
{% endblock linkcss %}

{% block title %} Create post {% endblock title %}

{% block content %}
    <main>
        <section>
            <h1>{{post.title}}</h1>
            <p>{{post.content}}</p>
        </section>
    </main>
{% endblock content %}

{% block javascript %} 


{% endblock javascript %}

Foro. Flask/foro/templates/post_create.html
{% extends 'base.html' %}

{% block linkcss %} 
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/posts/post_create.css') }}">
{% endblock linkcss %}

{% block title %} Create post {% endblock title %}

{% block content %}
    <main>
        <section class="create_post_container">
            <form method="POST" class="create_post_container_form">
                <label>Title:</label>
                <input type="text" name="title_post" placeholder="Post title..">
                <label>Content:</label>
                <textarea type="text" name="content_post" placeholder="Content about post.."></textarea>
                <button type="submit">CREATE</button>
            </form>
        </section>
    </main>
{% endblock content %}

{% block javascript %} 


{% endblock javascript %}

Foro. Flask/foro/templates/posts.html
{% extends 'base.html' %}

{% block linkcss %} 
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/posts/posts.css') }}">
{% endblock linkcss %}

{% block title %} {{category.name}} {% endblock title %}

{% block content %}
    <main>
        {% if not posts %}
            <section class="posts_container">
                <h1 class="if-not-post-h1" >There are no posts with the category: {{category.name}} but you can be the first to create a post.</h1>
                <a class="if-not-post-a"  href="{{url_for('views.create_post', category_id = category.id)}}">Create a new post of {{category.name}}</a>
            </section>
        {% else %}
        <section class="posts_container">
            <a class="if-not-post-a"  href="{{url_for('views.create_post', category_id = category.id)}}">Create a new post of {{category.name}}</a>
            <article class="posts_container_list">
                {% for user, post in posts %}
                    <div class="post_container">
                        <div class="post_container_header">
                            <img src="{{ url_for('static', filename='profilephotos/'+user.profile_photo) }}" alt="img user">
                            <h3>{{user.username}}</h3>
                        </div>
                        <h2><a href="{{url_for('views.post', category_id = category.id, title = post.title)}}">{{post.title}}</a></h2>
                    </div>
                {% endfor %}
            </article>
        </section>
        {% endif %}
    </main>
{% endblock content %}

{% block javascript %} 


{% endblock javascript %}

Foro. Flask/foro/templates/profile.html
{% extends 'base.html' %}

{% block linkcss %} 
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/profile/header.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/profile/main.css') }}">
{% endblock linkcss %}

{% block title %} {{user.username}} {% endblock title %}

{% block content %} 

<main>

    <section class="header_profile_container">
        <article class="header_container_banner">
            <img src="{{ url_for('static', filename='profilebanners/'+user.profile_banner) }}" alt="gif">

            <div class="header_container_banner_information">
                <h2>{{user.username}} |</h2>
                <h2>Last connection: {{user.last_connection}}</h2>
                <button><a href="{{url_for("views.profile_update", username = user.username)}}"><i class="bi bi-pencil-square"></i></a></button>
            <div>
        </article>

        <img class="img-profile" src="{{ url_for('static', filename='profilephotos/'+user.profile_photo) }}" alt="gif">
    </section>

    <section class="profile_main">

        <aside class="profile_information"> 
            <h2>Username: </h2>
            <p>{{user.username}}</p>

            <h2>Email: </h2>
            <p>{{user.email}}</p>

            <h2>Likes Gived: </h2>
            <p>{{user.likes|count}}⭐</p>

            <h2>Comments Made: </h2>
            <p>{{user.comments|count}}💬</p>
        </aside>

        <article class="profile_comments">
            <form method="POST" class="form_container">
                <h2>Leave a comment</h2>
                <textarea name="comment"></textarea>
                <button type="submit">SUBMIT</button>
            </form>
            
            {% for user, comment in comments %}
            <div class="comment_container">

                    <div class="comment_container_header">
                        <img  src="{{ url_for('static', filename='profilephotos/'+user.profile_photo) }}" alt="gif">
                        <h2>{{user.username}}</h2>


                        {% if current_user.id in comment.likes|map(attribute="user_id")|list %}
                        <a href="/{{user.username}}/{{comment.id}}/like" class="like_comment"><i class="bi bi-star-fill"></i></a><span class="like_comment_count">{{comment.likes|length}}</span>

                        {% else %}
                        <a href="/{{user.username}}/{{comment.id}}/like" class="like_comment"><i class="bi bi-star"></i></a><span class="like_comment_count">{{comment.likes|length}}</span>

                        {% endif %}

                        {% if comment.user_id == current_user.id or comment.profile_id == current_user.id %}
                            <a href="/{{user.username}}/{{comment.id}}/delete" class="trash_comment"><i class="bi bi-trash"></i></a>
                        {% endif %}
                    </div>

                    <p>{{comment.content}}</p>

            </div>
            {% endfor %}
        </article>

    </section>
</main>

{% endblock content %}

Foro. Flask/foro/templates/sign_up.html
{% extends 'base.html' %}

{% block linkcss %} <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/sign_up/sign_up.css') }}">{% endblock linkcss %}

{% block title %} Sign Up {% endblock title %}

{% block content %}
<main>
    <section class="form_login_center">
        <form method="POST" class="form_container">
            <label for="username">Username:</label>
            <input type="text" id="username" name="username">

            <label for="email">Email:</label>
            <input type="text" id="email" name="email">

            <label for="password">Password:</label>
            <input type="password" id="password" name="password">

            <label for="password">Confirm password:</label>
            <input type="password" id="confirm_password" name="confirm_password">
            
            <button type="submit">Sign Up</button>
        </form>
    </section>
</main>
{% endblock content %}

Foro. Flask/foro/templates/update.html
{% extends 'base.html' %}

{% block linkcss %} <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/profile/edit.css') }}">{% endblock linkcss %}

{% block title %} Editing: {{user.username}} {% endblock title %}

{% block content %}
<main>
    <section class="form_login_center">
        <form method="POST" class="form_container" enctype="multipart/form-data">
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" value="{{user.username}}">

            <label for="email">Email:</label>
            <input type="text" id="email" name="email" value="{{user.email}}">

            <label for="profile_photo" class="pfphoto">Profile photo:</label>
            <input type="file" accept="image/*" id="profile_photo" class="pfphoto" name="profile_photo">

            <div class="checkbox">
                <label for="cbox2">Remove profile photo</label>
                <input type="checkbox" id="removeprofilephoto" name="removeprofilephoto">
            </div>

            <label for="profile_banner" class="pfbanner">Profile banner:</label>
            <input type="file" accept="image/*" id="profile_banner" class="pfbanner" name="profile_banner">

            <div class="checkbox">
                <label for="cbox2">Remove profile banner</label>
                <input type="checkbox" id="removeprofilebanner" name="removeprofilebanner">
            </div>

            <label for="password">Password (ACTUAL):</label>
            <input type="password" id="password" name="password">
            
            <button type="submit">Edit</button>
        </form>
    </section>
</main>
{% endblock content %}

{% block javascript %} <script src="{{ url_for('static', filename='js/update/update.js') }}"> </script>{% endblock javascript %}